<?php

use Illuminate\Database\Seeder;
use App\komputer;

class KomputerTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pc = [
            [
                "kode" => "002/INSAN/52",
                "system" => "Windows 7 Pro",
                "nomor_ip" => "192.168.1.52",
                "motherboard" => "Amptron H55",
                "processor" => "Intel i3 Gen 1",
                "powersupply" => "Innovation 400W",
                "ram"   => "4GB DDR3",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 19 Inch",
                "monitor2" => "Tidak",
            ],
            [
                "kode" => "003/INSAN/53",
                "system" => "Windows 10 Pro",
                "nomor_ip" => "192.168.1.53",
                "motherboard" => "MSI Pro H51M Pro",
                "processor" => "Intel i5 Gen 10",
                "powersupply" => "Innovation 400W",
                "ram"   => "4GB DDR4",
                "disk"  => "SSD 248 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 19 Inch",
                "monitor2" => "Tidak",
            ],
            [
                "kode" => "004/INSAN/54",
                "system" => "Windows 10 Pro",
                "nomor_ip" => "192.168.1.54",
                "motherboard" => "MSI Pro H51M Pro",
                "processor" => "Intel i5 Gen 10",
                "powersupply" => "Innovation 400W",
                "ram"   => "4GB DDR4",
                "disk"  => "SSD 248 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 19 Inch",
                "monitor2" => "Tidak",
            ],
            [
                "kode" => "005/INSAN/55",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.55",
                "motherboard" => "Gigabyte H61M",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Iya",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "LG 14 Inch",
            ],
            [
                "kode" => "006/INSAN/56",
                "system" => "Windows 7",
                "nomor_ip" => "192.168.1.56",
                "motherboard" => "Gigabyte H61M",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],
            [
                "kode" => "007/INSAN/57",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.57",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],
            [
                "kode" => "008/INSAN/58",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.58",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "010/INSAN/60",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.60",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "011/INSAN/61",
                "system" => "Windows 7 Pro",
                "nomor_ip" => "192.168.1.61",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel i3 Gen 1",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "SSD 120 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "000/INSAN-BANK-DATA/00",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.00",
                "motherboard" => "Gigabyte",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "012/INSAN/62",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.62",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "013/INSAN/63",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.63",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "014/INSAN/64",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.64",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "015/INSAN/65",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.65",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "016/INSAN/66",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.66",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "017/INSAN/67",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.67",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "018/INSAN/68",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.68",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "019/INSAN/69",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.69",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "020/INSAN/70",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.70",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "021/INSAN/71",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.71",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "022/INSAN/72",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.72",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "023/INSAN/73",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.73",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "024/INSAN/74",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.58",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "025/INSAN/75",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.58",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "2GB DDR2",
                "disk"  => "Hardisk 250 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "026/INSAN/76",
                "system" => "Windows XP",
                "nomor_ip" => "192.168.1.58",
                "motherboard" => "Gigabyte H55",
                "processor" => "Intel Core 2 Duo",
                "powersupply" => "Advance 400W",
                "ram"   => "1GB DDR1",
                "disk"  => "Hardisk 50 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "000/INSAN-SERVER/11",
                "system" => "Windows Server",
                "nomor_ip" => "192.168.1.121",
                "motherboard" => "HP PRO Liant",
                "processor" => "Intel Xeon",
                "powersupply" => "Advance 400W",
                "ram"   => "4GB DDR3",
                "disk"  => "Hardisk 500 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 19 Inch",
                "monitor2" => "Tidak",
            ],

            [
                "kode" => "000/INSAN-SERVER/10",
                "system" => "Windows Server 2012",
                "nomor_ip" => "192.168.1.10",
                "motherboard" => "HP Pro Liant",
                "processor" => "Intel Xeon",
                "powersupply" => "HP 400W",
                "ram"   => "12 GB DDR4",
                "disk"  => "SSD 1000 GB + HDD 1000 GB + HDD 1000 GB",
                "vga"   => "Internal",
                "split" => "Tidak",
                "monitor1" => "LG 14 Inch",
                "monitor2" => "Tidak",
            ],
            ];

            komputer::insert($pc);
    }
}
